version: '3'
services:

  backend:
    container_name: test_backend
    build:
      context: .
      dockerfile: ./DockerfileBackend
    volumes:
      - ./server:/var/www/test
    working_dir: /var/www/test
    command: python main.py
    depends_on:
      - database
    ports:
      - 80:80
  database:
    image: mongo:latest
    ports:
      - 27017:27017